name: Build Ubuntu 18 package

on:
    pull_request:
        # We don't need this to be run on all types of PR behavior
        # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
        types:
          - opened
          - synchronize
          - edited

    # We want this run on a push to main, too, so that it creates
    # Github releases with permanent artifacts.
    push:
      branches:
        - main

jobs:
    build:
        name: Build Ubuntu 18 package
        runs-on: ubuntu-18.04
        steps:
          # This helps run the overall job faster
          - name: Disable initramfs update
            run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf

          # This helps run the overall job faster
          - name: Disable man-db update
            run: sudo rm -f /var/lib/man-db/auto-update

          - name: Install required packages
            run: |
              sudo apt update
              sudo apt install -y ubuntu-dev-tools gnupg debhelper dh-python \
                  python3-all-dev python3-setuptools python3-six python3-sphinx \
                  graphviz libcap-ng-dev libdpdk-dev libnuma-dev libpcap-dev \
                  libssl-dev pkg-config python-all-dev python-setuptools

          - name: Check out the code
            uses: actions/checkout@v2

          - name: Do the build
            run: $GITHUB_WORKSPACE/ubuntu18/build.sh

          - name: Upload the Ubuntu 18 artifact to the Github Action
            uses: actions/upload-artifact@v2
            with:
              name: ovs-ubuntu18
              path: ubuntu18/*.tar

          # If this was a merge to main, make a release so that the
          # artifact is kept permanently
          - name: Create release tag
            if: github.ref == 'refs/heads/main'
            run: |
              . $GITHUB_WORKSPACE/ubuntu18/env.sh
              echo "::set-output name=TAG::ovs_${SOURCE_PACKAGE_VERSION}${CISCO_VERSION}-build.${{ github.run_number }}"
            id: tag

          - name: Upload the Ubuntu 18 artifact to a Github release
            uses: ncipollo/release-action@v1
            if: github.ref == 'refs/heads/main'
            with:
              artifacts: "ubuntu18/*.tar"
              commit: ${{ github.sha }}
              tag: ${{ steps.tag.outputs.TAG }}
              token: ${{ github.token }}
